MyBlog/MyBlog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace="blog")),
    path('account/', include('account.urls', namespace="account")),
]

MyBlog/account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
    path("login/", views.user_login, name="user_login"),
    path("logout/", views.user_logout, name="user_logout"),
    path("register/", views.user_register, name="user_register"),
    path("userInfo/<user_id>", views.user_info, name="user_info"),
]

MyBlog/blog/urls.py
from django.urls import path
from . import views

app_name='blog'
urlpatterns = [
    path("blog_title", views.blog_title, name='blog_title'),
    path(r'content/<article_id>', views.blog_details, name='blog_details'),
]

MyBlog/account/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    birth = models.DateTimeField(blank=True)
    phone = models.CharField(max_length=20,blank=True)

MyBlog/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class BlogArticle(models.Model):
    title = models.CharField(max_length=300)
    author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
    content = models.TextField()
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

MyBlog/account/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm = forms.CharField(label='Confirm Password:', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username','email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] == cd['password2']:
            raise forms.ValidationError("password not match")
        return cd['password2']

class UserInfoForm(forms.Form):
    birth = forms.CharField()
    phone = forms.CharField()

MyBlog/account/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from . import forms, models

# Create your views here.

def user_login(request):
    if request.method == 'POST':
        login_form = forms.LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user:
                login(request,user)
                return HttpResponseRedirect("/blog/blog_title")
            else:
                return HttpResponse('your account or password error')
        else:
            return HttpResponse('invalid login')
    if request.method == 'GET':
        login_form = forms.LoginForm()
        return render(request, 'account/login.html', {'form': login_form})

def user_logout(request):
    logout(request)
    return HttpResponseRedirect("/blog/blog_title")

def user_register(request):
    if request.method == 'POST':
        user_form = forms.RegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return user_login(request)
        else:
            return HttpResponse(user_form)
    else:
        user_form = forms.RegisterForm()
        return render(request,'account/register.html', {'form': user_form})

def user_info(request, user_id):
    user = get_object_or_404(User, id=user_id)
    # User.objects.get()
    userInfos = models.UserInfo.objects.all()
    userInfo = None
    for userinfo in userInfos:
        if userinfo.user.id == int(user_id):
            userInfo = userinfo
    if request.method == 'POST':
        userInfo_form = forms.UserInfoForm(request.POST)
        if userInfo_form.is_valid():
            cd = userInfo_form.cleaned_data
            print(cd)
            if userInfo:
                userInfo.birth = cd['birth']
                userInfo.phone = cd['phone']
                userInfo.user = user
                userInfo.save()
            else:
                userInfo = models.UserInfo.objects.create(user=user,birth=cd['birth'],phone=cd['phone'])
                userInfo.save()
            return HttpResponseRedirect("/account/userInfo/"+user_id)
        else:
            return HttpResponse('form is invalid')
    else:
        return render(request, 'account/user_info.html',{'userInfo':userInfo})

MyBlog/blog/views.py
from django.shortcuts import render, get_object_or_404
from . import models

# Create your views here.

def blog_title(request):
    blogs = models.BlogArticle.objects.all()
    return render(request, 'blog/titles.html',{'blogs': blogs})

def blog_details(request,article_id):
    article = get_object_or_404(models.BlogArticle,id=article_id)
    # article = models.BlogArticle.objects.get(id=article_id)
    return render(request, 'blog/content.html', {'article': article})

MyBlog/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv=”X-UA-Compatible” content=”IE=Edge">
    <meta charset="UTF-8">
    <meta name=”viewport” content=”width=device-width, initial-scale=l”>
    <title>{% block title %}{% endblock %}</title>
    <link rel=”stylesheet” href=”http://necolas.github.io/normalize.css/”>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <div class="select2-container">
        {% block content %}{% endblock %}
    </div>
    <script src="http://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

MyBlog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv=”X-UA-Compatible” content=”IE=Edge">
    <meta charset="UTF-8">
    <meta name=”viewport” content=”width=device-width, initial-scale=l”>
    <title>{% block title %}{% endblock %}</title>
    <link rel=”stylesheet” href=”http://necolas.github.io/normalize.css/”>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    {% include 'header.html' %}
    <div class="select2-container">
        {% block content %}{% endblock %}
    </div>
    {% include 'footer.html' %}
    <script src="http://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

MyBlog/templates/blog/content.html
{% extends 'base.html' %}
{% block title %}{{ article.title }}{% endblock %}
{% block content %}
    <div>
    {{ article.content }}
    </div>
{% endblock %}

MyBlog/templates/blog/titles.html
{% extends 'base.html' %}
{% block title %}blog titles{% endblock %}
{% block content %}
    <ul>
        {% for blog in blogs %}
            <li>
                <a href="content/{{ blog.id }}">
                    {{ blog.title }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

MyBlog/templates/footer.html
<div class="container">
    <p class="text-center navbar-fixed-bottom">www.zhouyoulin.com </p>
</div>

MyBlog/templates/header.html
<div class="container" style="width: 100%;padding-right: 0px;padding-left: 0px">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Brand</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">Link</a></li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        {% if user.is_authenticated %}
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">{{ user.username }}<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="/account/userInfo/{{ user.id }}">My Info</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                            </ul>
                        {% else %}
                            <a href="{% url 'account:user_login' %}">Login</a>
                        {% endif %}
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</div>